# Generated by Django 5.0.4 on 2024-04-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_company_alter_customuser_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managing_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Finance'), (2, 'Stock Manager')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Manager'), (2, 'Cashier')], null=True),
        ),
    ]
