from django.urls import path
from . import views


app_name = 'inventory'
urlpatterns = [
    path('Branch/<int:branch_id>/', views.create_category, name='create_category'),
    path('category/<int:category_id>/edit/',
         views.edit_category, name='edit_category'),
    path('category/<int:category_id>/delete/',
         views.delete_category, name='delete_category'),
    path('category/<int:category_id>/',
         views.category_detail, name='category_detail'),
    path('category/<int:category_id>/create_product/',
         views.create_product, name='create_product'),
    path('category/<int:category_id>/',
         views.category_detail, name='category_detail'),
    path('create_product/<int:category_id>/',
         views.create_product, name='create_product'),
    path('edit_product/<int:product_id>/',
         views.edit_product, name='edit_product'),
    path('delete_product/<int:product_id>/',
         views.delete_product, name='delete_product'),
    path('suppliers/',
         views.suppliers, name='suppliers'),
    path('create_supplier/',
         views.create_supplier, name='create_supplier'),
    path('suppliers/<int:supplier_id>/edit/',
         views.edit_supplier, name='edit_supplier'),
    path('suppliers/<int:supplier_id>/delete/',
         views.delete_supplier, name='delete_supplier'),
    path('orders/',
         views.orders, name='orders'),
    path('create_order/',
         views.create_order, name='create_order'),
    path('orders/<int:order_id>/edit/', views.edit_order, name='edit_order'),
    path('receivings/',
         views.receivings, name='receivings'),
    path('orders/<int:order_id>/receive/',
         views.create_receiving, name='receive'),
    path('bills/',
         views.bills, name='bills'),
    path('generate-pdf/<int:bill_id>/',
         views.generate_pdf, name='generate_invoice'),
    path('receive/<int:product_id>/', views.receive_virtual_product,
         name='receive_vproduct'),
    path('vproducts/',
         views.vproducts, name='vproducts'),
    path('virtual_warehouse/',
         views.virtual_warehouse, name='virtual_warehouse'),
    path('issue/<int:virtual_product_id>/', views.issue_virtual_product,
         name='issue_vproduct'),
    path('transfers/',
         views.transfers, name='transfers'),
    path('create_product_transfer/',
         views.create_product_transfer, name='create_product_transfer'),
    path('transfers/<int:transfer_id>/receive/',
         views.receive_product_transfer, name='receive_product_transfer'),



]
