# Generated by Django 5.0.4 on 2024-04-24 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_supplier_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='products_supplied',
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_supplied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='inventory.product'),
        ),
    ]
