# Generated by Django 5.0.4 on 2024-04-25 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_receiving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiving',
            name='order_number',
        ),
        migrations.AddField(
            model_name='receiving',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.order'),
        ),
    ]
