# Generated by Django 5.0.4 on 2024-04-25 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_receiving_order_number_receiving_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
                ('receivings', models.ManyToManyField(to='inventory.receiving')),
            ],
        ),
    ]
