# Generated by Django 5.0.4 on 2024-04-25 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_bill_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='receivings',
        ),
        migrations.AddField(
            model_name='bill',
            name='receiving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.receiving'),
        ),
    ]
