# Generated by Django 5.0.4 on 2024-04-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_product_virtual_product_issuevirtual_receivevirtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuevirtual',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receivevirtual',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
