# Generated by Django 5.0.4 on 2024-04-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_issuevirtual_quantity_receivevirtual_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='virtual_product',
        ),
    ]
