# Generated by Django 5.0.4 on 2024-04-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_product_virtual_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivevirtual',
            name='issued',
            field=models.BooleanField(default=False),
        ),
    ]
