# Generated by Django 5.0.4 on 2024-04-28 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_producttransfer_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttransfer',
            name='from_branch',
        ),
    ]
