# Generated by Django 5.0.4 on 2024-05-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
