# Generated by Django 5.0.4 on 2024-05-10 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_rename_status_branch_active'),
        ('inventory', '0028_purchasesaccount_salesaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesaccount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_accounts', to='company.branch'),
        ),
        migrations.AddField(
            model_name='salesaccount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_accounts', to='company.branch'),
        ),
    ]
