# Generated by Django 5.0.4 on 2024-05-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_rename_price_product_buying_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default/default_product_image.png', null=True, upload_to='product_images'),
        ),
    ]
