# Generated by Django 5.0.4 on 2024-05-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_remove_product_branch_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default/default_product_image.jpg', null=True, upload_to='product_images'),
        ),
    ]
