# Generated by Django 5.0.4 on 2024-05-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default_product_image.jpg', null=True, upload_to='product_images'),
        ),
        migrations.CreateModel(
            name='CompositeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('components', models.ManyToManyField(blank=True, related_name='composite_of', to='inventory.product')),
            ],
        ),
    ]
