# Generated by Django 5.0.4 on 2024-05-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_remove_compositeproduct_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositeproduct',
            name='components',
            field=models.ManyToManyField(related_name='composite_of', to='inventory.product'),
        ),
    ]
