# Generated by Django 5.0.4 on 2024-05-12 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_adjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.adjustmentreason'),
        ),
    ]
