# Generated by Django 5.0.4 on 2024-05-13 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_rename_status_branch_active'),
        ('inventory', '0042_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='company.company'),
        ),
    ]
