# Generated by Django 5.0.4 on 2024-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_branches',
            field=models.IntegerField(default=0),
        ),
    ]
