# Generated by Django 5.0.4 on 2024-04-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_company_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
